### ISSUE TITLE
Is mark-thing-at-make-keybindings still a thing?

### ISSUE THREAD

**Issue by manuel-uberti** [plandes/mark-thing-at#1]
Hi,

thanks for this package. The README mentions `mark-thing-at-make-keybindings`, but I don't find it in the code. 

However, I see there is a `mark-thing-at-keymap-prefix` to possibly set a custom prefix.

Does the README need to reflect this?

**Comment by bbigras** [comment]
I have the same problem. I'm using melpa.

**Comment by manuel-uberti** [comment]
@plandes friendly ping. :)

**Comment by plandes** [comment]
Sorry all, this somehow got buried.  The variable @manuel-uberti mentions is an artifact from old code and I have updated the `README.md` to have the correct information, which is to customize the `mark-thing-at-keymap-prefix`.  However, the current Melpa version doesn't allow the best way to customize it.  I have fixed it, cut a new release, and within 24 hours will be available as version 0.0.2 as a package.  When that happens, will someone please let me know if it works for them or not?  Thanks in advance.

**Comment by manuel-uberti** [comment]
Thanks for the update. I'm actually happy with the default prefix, I opened this only to ask for a documentation update (especially since I mentioned `mark-thing-at-keymap-prefix` [here](https://www.manueluberti.eu/emacs/2020/04/13/lockdown-beam-mark-thing-at/)).

If it's OK with you, I am closing this because you fixed what I was asking for.

**Comment by plandes** [comment]
@manuel-uberti Thanks for the shout out and I'm really glad to hear things I write is appreciated and used by others.  Regarding a shell in Emacs, I don't specifically do any thing with completions, but my [bshell package](https://github.com/plandes/bshell) might address something you might be missing in the default Emacs shell.
